import { gql } from '@apollo/client'

export const DATA = gql`
  query{
  SHOP:shop{
    name,
    description
  },
  COLLECTIONS: collections(first: 20){
    edges{
      node{
        id
        title
        description
        image{
          src
        }
        products(first:20){
          edges{
            node{
              id
              title
              handle
              priceRange{
                maxVariantPrice{
                  amount
                },
                minVariantPrice{
                  amount
                }
              },
              media(first:1){
                edges{
                  node{
                    previewImage{
                      src,
                      altText,
                      width
                      height
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  PRODUCTS:products (first: 20){
    pageInfo{
      hasNextPage
      hasPreviousPage
    },
    edges{
      node{
        id
        title,
        description
        vendor,
        priceRange{
          minVariantPrice{
            amount
            currencyCode
          },
          maxVariantPrice{
            amount
            currencyCode
          }
        },
        images(first:10){
          edges{
            node{
              id
            	src
              width
              height
              altText
            }
          }
        },
        media(first: 1){
          edges{
            node{
              previewImage{
                src
                altText
              }
            }
          }
        }
        tags
        handle
        variants(first: 5, reverse:true){
          edges{
            node{
              id
              title
              image{
                src
              }
              price
            }
          }
        },
        
      }
    }
  }


}
`